configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/sandler-nlsandler%2Fminimal-todo-bc92d9525d3ca9002e6c6bdb1d00702feb32fb108c4f678a64048421f60a08ef.yml
openapi_spec_hash: bc2e30ddc6aaf8925cc0fdfbfe81c777
config_hash: b329babcdd518bf8a605f2a2694e1ff6
