configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/sandler-nlsandler%2Fminimal-todo-cbbc42da4fbddd7acf648a65d83b5ad4caac93f3909ac722718406eff7ddcb83.yml
openapi_spec_hash: a647efd404afd3e5892a8ce209c59aef
config_hash: b329babcdd518bf8a605f2a2694e1ff6
